### ISSUE TITLE
Tetrodotoxin 2.0

### ISSUE THREAD

**Issue by GHOST-PSYCHO** [Bhai4You/Hackstore#1]
I Want To Join Hackstore

Email : tetrodotoxin2.0@gmail.com

Facebook :~ https://facebook.com/Tetrodotoxin2.0

WhatsApp :~ +8801687262566

Instagram :~ @Tetrodotoxin2.0

**Comment by Bhai4You** [comment]
Done ^^
Thanks for Joining
