### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by LavSarkari** [Bhai4You/Hackstore#3]
### 1. Bro why its paid...
2.And please tell me when you will content me to talk about the project.....

**Comment by Bhai4You** [comment]
1. Paid for hardwork and time !! (Money > Good Server > Direct Download Features)
2. you are already in Hackstore Project ^^ you can any time change or add issues, courses, links, Apps and Books also you can share your knowlege for Imrovement.

Link :  https://github.com/users/Bhai4You/projects/1

if you found any critical issues or other personal talk then mail me at parixit1337@gmail.com
